# shapes.py>

def mario(np,arraiPosition):
    marron = (3,1,0)
    #marron = (26,5,1)
    #amarillo = (27,18,1)
    amarillo = (3,2,1)
    rojo = (2,0,0)


    np[arraiPosition[4][15]] = (rojo)
    np[arraiPosition[5][15]] = (rojo)
    np[arraiPosition[6][15]] = (rojo)
    np[arraiPosition[7][15]] = (rojo)
    np[arraiPosition[8][15]] = (rojo)

    np[arraiPosition[3][14]] = (rojo)
    np[arraiPosition[4][14]] = (rojo)
    np[arraiPosition[5][14]] = (rojo)
    np[arraiPosition[6][14]] = (rojo)
    np[arraiPosition[7][14]] = (rojo)
    np[arraiPosition[8][14]] = (rojo)
    np[arraiPosition[9][14]] = (rojo)
    np[arraiPosition[10][14]] = (rojo)
    np[arraiPosition[11][14]] = (rojo)

    np[arraiPosition[3][13]] = (marron)
    np[arraiPosition[4][13]] = (marron)
    np[arraiPosition[5][13]] = (marron)
    np[arraiPosition[6][13]] = (amarillo)
    np[arraiPosition[7][13]] = (amarillo)
    np[arraiPosition[8][13]] = (marron)
    np[arraiPosition[9][13]] = (amarillo)

    np[arraiPosition[2][12]] = (marron)
    np[arraiPosition[3][12]] = (amarillo)
    np[arraiPosition[4][12]] = (marron)
    np[arraiPosition[5][12]] = (amarillo)
    np[arraiPosition[6][12]] = (amarillo)
    np[arraiPosition[7][12]] = (amarillo)
    np[arraiPosition[8][12]] = (marron)
    np[arraiPosition[9][12]] = (amarillo)
    np[arraiPosition[10][12]] = (amarillo)
    np[arraiPosition[11][12]] = (amarillo)

    np[arraiPosition[2][11]] = (marron)
    np[arraiPosition[3][11]] = (amarillo)
    np[arraiPosition[4][11]] = (marron)
    np[arraiPosition[5][11]] = (marron)
    np[arraiPosition[6][11]] = (amarillo)
    np[arraiPosition[7][11]] = (amarillo)
    np[arraiPosition[8][11]] = (amarillo)
    np[arraiPosition[9][11]] = (marron)
    np[arraiPosition[10][11]] = (amarillo)
    np[arraiPosition[11][11]] = (amarillo)
    np[arraiPosition[12][11]] = (amarillo)

    np[arraiPosition[2][10]] = (marron)
    np[arraiPosition[3][10]] = (marron)
    np[arraiPosition[4][10]] = (amarillo)
    np[arraiPosition[5][10]] = (amarillo)
    np[arraiPosition[6][10]] = (amarillo)
    np[arraiPosition[7][10]] = (amarillo)
    np[arraiPosition[8][10]] = (marron)
    np[arraiPosition[9][10]] = (marron)
    np[arraiPosition[10][10]] = (marron)
    np[arraiPosition[11][10]] = (marron)

    np[arraiPosition[4][9]] = (amarillo)
    np[arraiPosition[5][9]] = (amarillo)
    np[arraiPosition[6][9]] = (amarillo)
    np[arraiPosition[7][9]] = (amarillo)
    np[arraiPosition[8][9]] = (amarillo)
    np[arraiPosition[9][9]] = (amarillo)
    np[arraiPosition[10][9]] = (amarillo)

    np[arraiPosition[3][8]] = (marron)
    np[arraiPosition[4][8]] = (marron)
    np[arraiPosition[5][8]] = (rojo)
    np[arraiPosition[6][8]] = (marron)
    np[arraiPosition[7][8]] = (marron)
    np[arraiPosition[8][8]] = (marron)

    np[arraiPosition[2][7]] = (marron)
    np[arraiPosition[3][7]] = (marron)
    np[arraiPosition[4][7]] = (marron)
    np[arraiPosition[5][7]] = (rojo)
    np[arraiPosition[6][7]] = (marron)
    np[arraiPosition[7][7]] = (marron)
    np[arraiPosition[8][7]] = (rojo)  
    np[arraiPosition[9][7]] = (marron)
    np[arraiPosition[10][7]] = (marron)  
    np[arraiPosition[11][7]] = (marron)

    np[arraiPosition[1][6]] = (marron)
    np[arraiPosition[2][6]] = (marron)
    np[arraiPosition[3][6]] = (marron)
    np[arraiPosition[4][6]] = (marron)
    np[arraiPosition[5][6]] = (rojo)
    np[arraiPosition[6][6]] = (rojo)
    np[arraiPosition[7][6]] = (rojo)
    np[arraiPosition[8][6]] = (rojo)  
    np[arraiPosition[9][6]] = (marron)
    np[arraiPosition[10][6]] = (marron)  
    np[arraiPosition[11][6]] = (marron)
    np[arraiPosition[12][6]] = (marron)

    np[arraiPosition[1][5]] = (amarillo)
    np[arraiPosition[2][5]] = (amarillo)
    np[arraiPosition[3][5]] = (marron)
    np[arraiPosition[4][5]] = (rojo)
    np[arraiPosition[5][5]] = (amarillo)
    np[arraiPosition[6][5]] = (rojo)
    np[arraiPosition[7][5]] = (rojo)
    np[arraiPosition[8][5]] = (amarillo)  
    np[arraiPosition[9][5]] = (rojo)
    np[arraiPosition[10][5]] = (marron)  
    np[arraiPosition[11][5]] = (amarillo)
    np[arraiPosition[12][5]] = (amarillo)

    np[arraiPosition[1][4]] = (amarillo)
    np[arraiPosition[2][4]] = (amarillo)
    np[arraiPosition[3][4]] = (amarillo)
    np[arraiPosition[4][4]] = (rojo)
    np[arraiPosition[5][4]] = (rojo)
    np[arraiPosition[6][4]] = (rojo)
    np[arraiPosition[7][4]] = (rojo)
    np[arraiPosition[8][4]] = (rojo)  
    np[arraiPosition[9][4]] = (rojo)
    np[arraiPosition[10][4]] = (amarillo)  
    np[arraiPosition[11][4]] = (amarillo)
    np[arraiPosition[12][4]] = (amarillo)

    np[arraiPosition[1][3]] = (amarillo)
    np[arraiPosition[2][3]] = (amarillo)
    np[arraiPosition[3][3]] = (rojo)
    np[arraiPosition[4][3]] = (rojo)
    np[arraiPosition[5][3]] = (rojo)
    np[arraiPosition[6][3]] = (rojo)
    np[arraiPosition[7][3]] = (rojo)
    np[arraiPosition[8][3]] = (rojo)  
    np[arraiPosition[9][3]] = (rojo)
    np[arraiPosition[10][3]] = (rojo)  
    np[arraiPosition[11][3]] = (amarillo)
    np[arraiPosition[12][3]] = (amarillo)

    np[arraiPosition[3][2]] = (rojo)
    np[arraiPosition[4][2]] = (rojo)
    np[arraiPosition[5][2]] = (rojo)
    np[arraiPosition[8][2]] = (rojo)  
    np[arraiPosition[9][2]] = (rojo)
    np[arraiPosition[10][2]] = (rojo)  

    np[arraiPosition[2][1]] = (marron)
    np[arraiPosition[3][1]] = (marron)
    np[arraiPosition[4][1]] = (marron)
    np[arraiPosition[9][1]] = (marron)
    np[arraiPosition[10][1]] = (marron)
    np[arraiPosition[11][1]] = (marron)

    np[arraiPosition[1][0]] = (marron)
    np[arraiPosition[2][0]] = (marron)
    np[arraiPosition[3][0]] = (marron)
    np[arraiPosition[4][0]] = (marron)
    np[arraiPosition[9][0]] = (marron)
    np[arraiPosition[10][0]] = (marron)
    np[arraiPosition[11][0]] = (marron)
    np[arraiPosition[12][0]] = (marron)

    np.write()